name: thaki
description: Thaki Mobile Parking

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+19

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.0.5+1
  http: ^0.12.2
  crypto: ^2.1.5
  intl: ^0.16.1
  sqflite: ^1.3.1+1
  mutex: ^1.1.0
  email_validator: ^1.0.0
  url_launcher: ^5.5.0
  connectivity: '>=0.4.8+2 <2.0.0'
  shared_preferences: ^0.5.7
  store_redirect: ^1.0.2
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.8.1
  curved_navigation_bar: ^0.3.0
  flutter_datetime_picker:
    git:
      url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
      ref: patch-1 # Branch name
  package_info: ^0.4.1
  carousel_slider: ^3.0.0
  firebase_messaging: ^7.0.0
  firebase_analytics: ^6.0.1
  flutter_slidable: ^0.5.7
  qr_flutter: ^3.2.0
  image_cropper: ^1.2.2
  image_picker: ^0.6.7+22
  encrypt: ^4.1.0
  credit_card_validator: ^1.2.0
  webview_flutter: ^0.3.22+1
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.1
  twitter_login: ^2.1.4
  flutter_inappwebview: ^4.0.0
  flutter_facebook_auth: ^2.0.2
  pin_code_fields: ^5.2.0
  regexed_validator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_intl:
  enabled: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: fonts/Almarai/Almarai-Bold.ttf
          weight: 600
        - asset: fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
    - family: BwModelica
      fonts:
        - asset: fonts/BwModelica/BwModelica-Hairline.otf
          weight: 100
        - asset: fonts/BwModelica/BwModelica-HairlineItalic.otf
          weight: 100
          style: italic
        - asset: fonts/BwModelica/BwModelica-Thin.otf
          weight: 200
        - asset: fonts/BwModelica/BwModelica-ThinItalic.otf
          weight: 200
          style: italic
        - asset: fonts/BwModelica/BwModelica-Light.otf
          weight: 300
        - asset: fonts/BwModelica/BwModelica-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/BwModelica/BwModelica-Regular.otf
        - asset: fonts/BwModelica/BwModelica-RegularItalic.otf
          style: italic
        - asset: fonts/BwModelica/BwModelica-Medium.otf
          weight: 500
        - asset: fonts/BwModelica/BwModelica-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/BwModelica/BwModelica-Bold.otf
          weight: 600
        - asset: fonts/BwModelica/BwModelica-BoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/BwModelica/BwModelica-ExtraBold.otf
          weight: 700
        - asset: fonts/BwModelica/BwModelica-ExtraBoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/BwModelica/BwModelica-Black.otf
          weight: 800
        - asset: fonts/BwModelica/BwModelica-BlackItalic.otf
          weight: 800
          style: italic